// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/user/page": {
    params: {};
  };
  "/user/products": {
    params: {};
  };
  "/user/sales-orders": {
    params: {};
  };
  "/user/valorations": {
    params: {};
  };
  "/user/statistics": {
    params: {};
  };
  "/user/settings": {
    params: {};
  };
  "/product/new": {
    params: {};
  };
  "/product/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/inventory": {
    params: {};
  };
  "/admin/transactions": {
    params: {};
  };
  "/admin/valorations": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/product/:id" | "/login" | "/signup" | "/user/page" | "/user/products" | "/user/sales-orders" | "/user/valorations" | "/user/statistics" | "/user/settings" | "/product/new" | "/product/:id/edit" | "/admin" | "/admin/users" | "/admin/inventory" | "/admin/transactions" | "/admin/valorations" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/" | "/product/:id";
  };
  "routes/product/product-list.tsx": {
    id: "routes/product/product-list";
    page: "/";
  };
  "routes/product/product-detail.tsx": {
    id: "routes/product/product-detail";
    page: "/product/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/user.tsx": {
    id: "routes/user";
    page: "/user/page" | "/user/products" | "/user/sales-orders" | "/user/valorations" | "/user/statistics" | "/user/settings" | "/product/new" | "/product/:id/edit";
  };
  "routes/user/user-page.tsx": {
    id: "routes/user/user-page";
    page: "/user/page";
  };
  "routes/user/user-products.tsx": {
    id: "routes/user/user-products";
    page: "/user/products";
  };
  "routes/user/user-sales-orders.tsx": {
    id: "routes/user/user-sales-orders";
    page: "/user/sales-orders";
  };
  "routes/user/user-valorations.tsx": {
    id: "routes/user/user-valorations";
    page: "/user/valorations";
  };
  "routes/user/user-statistics.tsx": {
    id: "routes/user/user-statistics";
    page: "/user/statistics";
  };
  "routes/user/user-settings.tsx": {
    id: "routes/user/user-settings";
    page: "/user/settings";
  };
  "routes/product/product-new.tsx": {
    id: "routes/product/product-new";
    page: "/product/new";
  };
  "routes/product/product-edit.tsx": {
    id: "routes/product/product-edit";
    page: "/product/:id/edit";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/users" | "/admin/inventory" | "/admin/transactions" | "/admin/valorations";
  };
  "routes/admin/admin-dashboard.tsx": {
    id: "routes/admin/admin-dashboard";
    page: "/admin";
  };
  "routes/admin/admin-users.tsx": {
    id: "routes/admin/admin-users";
    page: "/admin/users";
  };
  "routes/admin/admin-inventory.tsx": {
    id: "routes/admin/admin-inventory";
    page: "/admin/inventory";
  };
  "routes/admin/admin-transactions.tsx": {
    id: "routes/admin/admin-transactions";
    page: "/admin/transactions";
  };
  "routes/admin/admin-valorations.tsx": {
    id: "routes/admin/admin-valorations";
    page: "/admin/valorations";
  };
  "routes/error-page.tsx": {
    id: "routes/error-page";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/product/product-list": typeof import("./app/routes/product/product-list.tsx");
  "routes/product/product-detail": typeof import("./app/routes/product/product-detail.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/user": typeof import("./app/routes/user.tsx");
  "routes/user/user-page": typeof import("./app/routes/user/user-page.tsx");
  "routes/user/user-products": typeof import("./app/routes/user/user-products.tsx");
  "routes/user/user-sales-orders": typeof import("./app/routes/user/user-sales-orders.tsx");
  "routes/user/user-valorations": typeof import("./app/routes/user/user-valorations.tsx");
  "routes/user/user-statistics": typeof import("./app/routes/user/user-statistics.tsx");
  "routes/user/user-settings": typeof import("./app/routes/user/user-settings.tsx");
  "routes/product/product-new": typeof import("./app/routes/product/product-new.tsx");
  "routes/product/product-edit": typeof import("./app/routes/product/product-edit.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin/admin-dashboard": typeof import("./app/routes/admin/admin-dashboard.tsx");
  "routes/admin/admin-users": typeof import("./app/routes/admin/admin-users.tsx");
  "routes/admin/admin-inventory": typeof import("./app/routes/admin/admin-inventory.tsx");
  "routes/admin/admin-transactions": typeof import("./app/routes/admin/admin-transactions.tsx");
  "routes/admin/admin-valorations": typeof import("./app/routes/admin/admin-valorations.tsx");
  "routes/error-page": typeof import("./app/routes/error-page.tsx");
};