// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/product/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/product/new": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/product/:id" | "/product/:id/edit" | "/product/new" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/" | "/product/:id" | "/product/:id/edit" | "/product/new" | "/*";
  };
  "routes/product-list.tsx": {
    id: "routes/product-list";
    page: "/";
  };
  "routes/product-detail.tsx": {
    id: "routes/product-detail";
    page: "/product/:id";
  };
  "routes/product-edit.tsx": {
    id: "routes/product-edit";
    page: "/product/:id/edit";
  };
  "routes/product-new.tsx": {
    id: "routes/product-new";
    page: "/product/new";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/product-list": typeof import("./app/routes/product-list.tsx");
  "routes/product-detail": typeof import("./app/routes/product-detail.tsx");
  "routes/product-edit": typeof import("./app/routes/product-edit.tsx");
  "routes/product-new": typeof import("./app/routes/product-new.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};